#!/bin/bash

filename="";

if [ -n "$1" ]; then
	if [ -f ~/shell-playground/templates/$1 ]; then
		if [ -n "$2" ]; then
			filename=$2;
		else
			filename=$1;
		fi
		if [ -f "$filname" ]; then
			echoerr "This file [$filename] already exists">&2
			exit 1
		else
			cat ~/shell-playground/templates/$1 > $filename 
			vim "$filename"
		fi
	else
		echoerr "ERROR: template $1 does not exit"
		echo -e "Here is a list of templates available:\n$(ls \
		~/shell-playground/templates)"
	fi
else
	echoerr "ERROR: no template entered"
fi


